version: '3.8'

services:
  # db:
  #   image: postgres:16.2
  #   environment:
  #     POSTGRES_DB: myproject
  #     POSTGRES_USER: myprojectuser
  #     POSTGRES_PASSWORD: myprojectsecretpassword
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    # depends_on:
    #   - db:
    #       condition: service_healthy
    #   - redis:
    #       condition: service_healthy

    command: python barda/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/barda
    ports:
      - "8000:8000"
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=myproject
    #   - DB_USER=myprojectuser
    #   - DB_PASSWORD=myprojectsecretpassword

# volumes:
#   postgres_data:
