version: '3.8'
secrets:
  db_password:
    file: ./configs/secrets/db_password.txt
services:
  db:
    image: postgres:16.2
    restart: always
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

    ports:
      - "5432:5432"

  lief:
    build: .
    restart: always
    depends_on:
      - db
          # condition: service_healthy
    #   - redis:
    #       condition: service_healthy

    command: python barda/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/barda
    secrets:
      - db_password
    ports:
      - "8000:8000"
